### ISSUE TITLE
More than 15 minutes

### ISSUE THREAD

**Issue by dragoncity17** [Admonstrator/purge-msoffice#1]
Hello,
Work perfectly thank you !!! :)

Just is very long... more than 15minutes (or 20-25 minutes... !) for remove office 365 o_O (with intel i5).

There is an solution to make it go faster?

Thank you again ! :)

**Comment by admonstrator** [comment]
Hi,

that's pretty normal tbh. Removal of O365 needs much time due to Microsoft stuff.
