### ISSUE TITLE
Tool doesn't work anymore?

### ISSUE THREAD

**Issue by emilianpr** [Admonstrator/purge-msoffice#2]
Hello, i get this error whenever im trying to run the tool. I use it very often as i configure computers for work porpuses

![Screenshot 2024-10-07 100309](https://github.com/user-attachments/assets/0c678e8e-5533-4d45-b29f-bc04d7e85039)

**Comment by admonstrator** [comment]
Thanks for letting me know, I will check this!

**Comment by emilianpr** [comment]
Sorry, also forgot to mention that the PC's are in a domain

**Comment by emilianpr** [comment]
Solved it, did it again on a new pc, i think this happens when the PC is in the domain, my bad! But thank you for the response :)

**Comment by admonstrator** [comment]
Glad to hear! I assume your domain policy might block the download (maybe because of anti-virus)
